# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 10.20

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: NeuVectorScan@3
  inputs:
    scanType: 'standalone'
    nvContainerRegistry: 'nvlab docker hub'
    nvRepository: 'neuvector/scanner'
    nvTag: 'latest'
    containerRegistry: 'lsong docker hub'
    repository: 'songlongtj/alpine'
    tag: '3.6'
